#ifndef COMMUNICATION_H
#define COMMUNICATION_H

#include "sys.h"
enum DATA_TYPE
{
    DATA_TYPE_NONE = 0,
    DATA_TYPE_QUAT = 1,
    DATA_TYPE_ACCEL = DATA_TYPE_QUAT << 1,
    DATA_TYPE_GYRO = DATA_TYPE_ACCEL << 1,
    DATA_TYPE_EULER = DATA_TYPE_GYRO << 1,
    DATA_TYPE_COMMAND = DATA_TYPE_EULER << 1,
    DATA_TYPE_PARAM = DATA_TYPE_COMMAND << 1,
    DATA_TYPE_MESSAGE = DATA_TYPE_PARAM << 1,
    DATA_TYPE_ALL = DATA_TYPE_QUAT | DATA_TYPE_ACCEL | DATA_TYPE_GYRO | DATA_TYPE_EULER
        | DATA_TYPE_COMMAND | DATA_TYPE_PARAM | DATA_TYPE_MESSAGE
};

enum COMMAND_TYPE
{
    COMMAND_TYPE_NONE = 0,
    COMMAND_TYPE_RUN = 1,
    COMMAND_TYPE_RESTART = COMMAND_TYPE_RUN << 1,
    COMMAND_TYPE_SEND_QUAT = COMMAND_TYPE_RESTART << 1,
    COMMAND_TYPE_SEND_ACCEL = COMMAND_TYPE_SEND_QUAT << 1,
    COMMAND_TYPE_SEND_GYRO = COMMAND_TYPE_SEND_ACCEL << 1,
    COMMAND_TYPE_All = COMMAND_TYPE_RUN | COMMAND_TYPE_RESTART
        | COMMAND_TYPE_SEND_QUAT | COMMAND_TYPE_SEND_ACCEL | COMMAND_TYPE_SEND_GYRO
};

void MyCOM_Init(void);
void MyCOM_SendData(const void *data,uint8_t dataType);
void MyCOM_GetData(void);
bool MyCOM_GetCOMMAND(uint8_t *needCmd);

#endif
